apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ["alertmanager:9093"]

    rule_files:
      - "alert.rules.yml"

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "nginx"
        static_configs:
          - targets: ["web-exporter:9113"]

  alert.rules.yml: |
    groups:
      - name: basic
        rules:
          - alert: TargetDown
            expr: up == 0
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Target {{ $labels.job }} лежить уже хвилину"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    route:
      receiver: "web-server-status"

    receivers:
      - name: "web-server-status"
        webhook_configs:
          - url: "http://alertmanager-discord:9094/webhook"
            send_resolved: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: monitoring
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
 
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
 
        location /stub_status {
            stub_status;
            allow all;
        }
    }