name: Build and Push Images to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  SERVICES_PATH: lab-monitoring/03-aws-ecs/services
  ECS_CLUSTER: lab-ecs-cluster

permissions:
  id-token: write   # для OIDC-автентифікації в AWS
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        service: [web, prometheus, grafana, alertmanager]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::132977458933:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and push ${{ matrix.service }}
        id: build
        uses: ./.github/actions/build-push-ecr
        with:
          ecr-repository: lab-monitoring-${{ matrix.service }}
          build-context: ${{ env.SERVICES_PATH }}/${{ matrix.service }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Show pushed image
        run: |
          echo 'Pushed image: ${{ steps.build.outputs.image-uri }}'

  deploy:
    needs: build-and-push   # чекає, поки всі 4 образи будуть зібрані й запушені
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ecs-service: [web-service, monitoring-service]

    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::132977458933:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Force new deployment for ${{ matrix.ecs-service }}
        run: |
          aws ecs update-service \
            --cluster "${{ env.ECS_CLUSTER }}" \
            --service "${{ matrix.ecs-service }}" \
            --force-new-deployment \
            --region "${{ env.AWS_REGION }}"